### ISSUE TITLE
Create plugins & data folder on startup.

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#100]
### Description
When just downloading a Chatoverflow Release as zip and running the shell script you don't have a plugins or a data folder in your directory. 

These should automatically be created by the framework or the bootstrap launcher to make the usage easier.

**Comment by sebinside** [comment]
Both, same with the Config folder.

**Comment by hlxid** [comment]
Creation of the plugin, data and config folder on framework startup is implemented in 8497176c2c9c95bba9dc82b14027200e71b76dbc.
Creation of these folders in the bootstrap launcher isn't really feasible because users may change the directories using cli flags which aren't parsed in the bootstrap launcher.
