### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#101]
### Description
Do we want to include an update checker in the bootstrap launcher that checks if a new version of codeoverflow is avialable? 

This could simply be done by having a simple text or json file in the main repo that contains the current version and checking it against the name of the jar.

We could even automatically download the new release without bigger changes to the bootstrap launcher.

**Comment by sebinside** [comment]
Good idea, if the bootstrap launcher does not change 😄

**Comment by hlxid** [comment]
We can even get the latest release using the [GitHub API](https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository) which also supplies us with a download link. Having to update a file manually makes the release process more stressful in my opinion.

The only problem left is that the required dependencies for the framework are stored in the jar of the bootstrap launcher. I think that we have the following two options:

1. Move the `dependencies.xml` file into the jar of the framework. This way the file gets updated when we download the new framework jar.
2. Download the new bootstrap jar and restart the bootstrap launcher with the new `dependencies.xml` file.

I prefer the latter, because the way to start the framework might change in the future and by keeping the bootstrap launcher up to date the user never has to download a fresh copy because the bootstrap launcher became incompatible.

Comments @sebinside @joblo2213?

**Comment by sebinside** [comment]
Creating a separate Updater which can also update the bootstrap launcher sounds way more flexible 👍

**Comment by hlxid** [comment]
The implementation in the `feature/101-deployment-updater` branch is now finished: https://github.com/codeoverflow-org/chatoverflow/compare/develop...feature/101-deployment-updater.

For testing purposes I've created a fake pre-alpha 3 and alpha 1 release at my [fork](https://github.com/daniel0611/chatoverflow/releases) which contain the new updater to demonstrate how the updater works. To test it, you can just download my fake pre-alpha 3 release, which wants to update itself to the fake alpha 1 release from my fork at startup.

Currently the actual updater is in the `ChatOverflow.jar` file and the bootstrap launcher is in the `ChatOverflow-Launcher.jar`. Do we want to move the bootstrap launcher to the `bin/` directory? I think it is bit confusing for people that start the jars themselves and don't use the start scripts. They maybe don't know which jar they should use.

@sebinside could you take a look on my changes when you have some spare time and make sure that you are fine with them, it's a rather big change.

**Comment by sebinside** [comment]
I will, but let me finish #40 first. Currently not that much time available... bummer.

**Comment by sebinside** [comment]
And yes, moving it to `bin/` sounds like a good idea. I already see them coming, trying to double click on a jar...

**Comment by hlxid** [comment]
Launcher has now been moved to `bin/` in d142635a26918d37fc287ed185e60b1b06fb1366.

**Comment by sebinside** [comment]
Tested the updater and looked into the code. Works like a charm, can be merged. Thank you!
