### ISSUE TITLE
Add delete button for plugin requirements to BetterREPL

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#60]
The better REPL should have a button to remove previously created requirements.

Currently the only way of removing them is editing the config file manually which is especally annoying when working with the testall plugin.

**Comment by sebinside** [comment]
Requirements are implicitly created in the plugin creation process. There is currently no functionality to add or delete them by yourself, only to change its value. 

Even worse, trough the bug #35 the xml loading does not handle missing values correctly and asumes, that there is a set requirement - but without value. This has to be fixed first.

**Comment by J0B10** [comment]
I actually meant delting the values (make them not set.)

**Comment by sebinside** [comment]
Okay, this will be also solved with #35.

**Comment by sebinside** [comment]
The problem was solved with issue #35. The newest version of the gui contains the `remove`-button, to unset a requirement.

But for some strange reason, the `sbt gui` command, does not copy the newest version. Is this worth a separate issue or just my fault? `ng serve` works just fine. @daniel0611 

Edit: The relevant commit codeoverflow-org/chatoverflow-gui@f391f470020cb01fa8ab9a705c0773399c3a2963

**Comment by hlxid** [comment]
Hmmm, after pulling the newest version `sbt gui` has done a rebuild for me. @sebinside you can try `sbt clean gui` to trigger a force-rebuild.

**Comment by sebinside** [comment]
My fault, chrome cached the site.
