### ISSUE TITLE
Auto generate methods to register event handlers

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#70]
### Description
For easier use every Event Input should have an individual method that registers an handler for each  Event. This method should be defined in the input as default method and should call the more generic `registerEventHandler()`.

To save some time and prevent repetative work there should be an sbt task to auto generate these methods.

### References
#36 -  _Rework stat and event input in the API_

**Comment by sebinside** [comment]
Note: The usage of this task should be optional, since it is not required to have a clean interface. If we add generator-logic at every end or even worse, mix it with handwirtten logic, no third-party developers will understand anything.

So, the sbt task will only help generate some methods, not generate complete files.

**Comment by sebinside** [comment]
Already solved through #114

**Comment by hlxid** [comment]
#114 reduces the boilerplate in the optionally `Listener <---> Connector` and the `Connector <---> In/Output` communication using generics. This issue is about the boilerplate in the `In/Output <---> Plugin` communication which can't be further be reduced using generics, because we want to have a method per event type in the api. Using generics for this was done in #36.

**Comment by sebinside** [comment]
Closing this for now, since it's kinda outdated. If we encounter similar problems in alpha 1, a new issue should be opened.
